### ISSUE TITLE
Peer connection doesn't work on MX Linux 23.3

### ISSUE THREAD

**Issue by FlowXP** [leon3s/wireguard-gui#115]
Hello,
the icon looks green, but I have no ping in any connection.
No ideea what is missing or why is not working, no error message.

**Comment by leon3s** [comment]
Ah i see, do you have wg-quick and zenity installed ?

**Comment by FlowXP** [comment]
wg-quick yes / zenity **no**
I thought that appimages have everything needed

**Comment by FlowXP** [comment]
wg-quick and zenity are installed, same result

**Comment by leon3s** [comment]
To avoid running the app as root i did setup a script that ask for the password when you apply a connection.
The script require wg-quick and zenity.

I'll setup a MX Linux vm during the week and see what's going on and get back to you!

**Comment by FlowXP** [comment]
honestly I was hoping so it would **not** ask for the root password, just like the VPN connections from KDE Plasma.

**Comment by leon3s** [comment]
I just release a new version with a better error handling. And i tested it on a fresh MXLinux install.
Apparently resolvconf was missing and i had to install it with wireguard and zenity.
I'll see if i can find a workarround for the root password.

**Comment by leon3s** [comment]
Closing this as i think it have been resolved.

**Comment by FlowXP** [comment]
> Closing this as i think it have been resolved.

Sry, but no, I still can't connect with the Appimage.
Also the vpn-s are not name sorted.

**Comment by leon3s** [comment]
Could you try with the latest release 0.1.3 please ? i just released it

**Comment by leon3s** [comment]
It should show an error message if something when wrong

**Comment by FlowXP** [comment]
> Closing this as i think it have been resolved.

Sry, but no, I still can't connect with the Appimage.
Also the vpn-s are not name sorted.
![Screenshot_20240804_184838](https://github.com/user-attachments/assets/65060d0d-97f9-471c-8a2b-572f23afbdf2)

**Comment by leon3s** [comment]
It says incorrect password attempts, i believe we can ignore other warnings.

You had a popup asking for your password ?

**Comment by FlowXP** [comment]
no, only that warning

**Comment by leon3s** [comment]
Could you try to install:

```sh
sudo apt-get install librsvg2-bin
```

**Comment by FlowXP** [comment]
I did and it's still the same error

**Comment by leon3s** [comment]
Can you check that you have ```libpixbufloader-svg.so``` somewhere in your system ?

**Comment by FlowXP** [comment]
I do, in 2 locations :
 /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/

/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/23.08/...../files/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/

**Comment by leon3s** [comment]
The new version 0.1.4 doesn't depend on zenity anymore and may have fix the problem

**Comment by FlowXP** [comment]
So far so good ! It's working !
I will test this in a clean VM, just to be sure.
THANK YOU !
But please please, sort the profiles alphabetically, I have a lot of them and it's not easy finding the one I need

**Comment by leon3s** [comment]
The new version 0.1.5 sort profiles alphabetically and i'have added a search bar

**Comment by FlowXP** [comment]
You are awesome !!
May I suggest for case normalization in search ?
If for ex I have a profile named "FINT" and I press "f" in the search box, I will never find it.
Thank you
